services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: dockerfile
      target: prod
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - SERVER_PATH=http://server:8080/api/v1
      - NEXT_PUBLIC_SERVER_PATH=http://localhost:8080/api/v1
      - CLIENT_PATH=http://client:3000
      - NEXT_PUBLIC_CLIENT_PATH=http://client:3000
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M