services:
  activemqt:
    container_name: jms-activemq
    image: rmohr/activemq
    ports:
      - "61616:61616"
      - "8161:8161"
  sensor-1:
    container_name: jms-message-sensor-1
    build:
      context: ./sensor
      dockerfile: Dockerfile
    environment:
      - URL_BROKER=tcp://activemqt:61616
      - CLIENT_PROVIDER=1
      - ACTIVEMQ_USERNAME=admin
      - ACTIVEMQ_PASSWORD=admin
      - TIME_OUT=10000
    depends_on:
      - activemqt
  sensor-2:
    container_name: jms-message-sensor-2
    build:
      context: ./sensor
      dockerfile: Dockerfile
    environment:
      - URL_BROKER=tcp://activemqt:61616
      - CLIENT_PROVIDER=2
      - ACTIVEMQ_USERNAME=admin
      - ACTIVEMQ_PASSWORD=admin
      - TIME_OUT=10000
    depends_on:
      - activemqt
  db:
    container_name: jms-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jms
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
  pgadmin:
    container_name: jms-pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@jms.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "80:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
  server:
      container_name: jms-message-server
      build:
        context: ./server
        dockerfile: Dockerfile
      ports:
        - "8081:8080"
      environment:
        - URL_BROKER=tcp://activemqt:61616
        - ACTIVEMQ_USERNAME=admin
        - ACTIVEMQ_PASSWORD=admin
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=jms
      depends_on:
        - db
        - activemqt
        - sensor-1
        - sensor-2
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 512M
          reservations:
            cpus: '0.25'
            memory: 256M
  astro:
    container_name: jms-message-astro
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - API_URL=http://server:8080
      - HOST=0.0.0.0
    ports:
      - "8080:4321"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    depends_on:
      - server

volumes:
  db-data: {}
  pgadmin-data: {}
  node_modules: {}
