services:
  redis:
      image: redis
      container_name: redis
      restart: always
      ports:
        - "6379:6379"
      command: ["redis-server", "--appendonly", "yes"]
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - server/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    depends_on:
      - db
    environment:
       - PGADMIN_PORT=${PGADMIN_PORT}
    ports:
      - "${PGADMIN_PORT}:80"
    env_file:
      - server/.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  server:
    # build:
    #   context: ./server
    #   dockerfile: dockerfile
    image: nightmarevco/mockify-load-balancers:server
    env_file:
      - server/.env
    depends_on:
      - db
      - redis
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
  apache-proxy:
      image: httpd:2.4
      container_name: apache_proxy
      restart: always
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
        - /etc/letsencrypt/live/mockify.steven-mateo.systems:/etc/letsencrypt/live/mockify.steven-mateo.systems:ro
      depends_on:
        - haproxy
        - client
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - server
  client:
    container_name: client
    # build:
    #   context: ./client
    #   dockerfile: dockerfile
    image: nightmarevco/mockify-load-balancers:client
    env_file:
      - client/.env
    ports:
      - "8080:3000"
    depends_on:
      - server
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

volumes:
  db-data: {}
  pgadmin-data: {}