services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: dockerfile
      target: prod
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "${PORT:-8080}:3000"
    depends_on:
      - server
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
