services:
  app-prod:
    container_name: app-prod
    build:
      context: .
      dockerfile: dockerfile
      target: prod
    environment:
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
  app-client:
    container_name: app-client
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - app-prod
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
