FROM eclipse-temurin:21-alpine AS builder

WORKDIR /app

COPY gradlew .
COPY gradle/wrapper gradle/wrapper
COPY build.gradle .
COPY settings.gradle .
COPY src src

RUN ./gradlew bootJar --no-daemon

FROM eclipse-temurin:21-alpine AS prod

WORKDIR /app

COPY --from=builder /app/build/libs/mvc-1.0.0.jar app.jar

EXPOSE 8080

RUN mkdir -p /app/logs
VOLUME ["/app/logs"]

ENTRYPOINT ["java", "-jar", "app.jar"]