FROM eclipse-temurin:21-alpine AS builder

WORKDIR /app

COPY gradlew .
COPY gradle/wrapper gradle/wrapper
COPY build.gradle .
COPY settings.gradle .
COPY src src

RUN ./gradlew shadowJar --no-daemon

FROM eclipse-temurin:21-alpine AS prod

WORKDIR /app

COPY --from=builder /app/build/libs/JMS-provider-1.0.0-all.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]