FROM eclipse-temurin:21-alpine AS builder

WORKDIR /app

COPY gradlew .
COPY gradle/wrapper gradle/wrapper
COPY build.gradle .
COPY settings.gradle .
COPY src src

RUN ./gradlew bootJar --no-daemon

# Prod Mode
FROM eclipse-temurin:21-alpine AS prod

WORKDIR /app

COPY --from=builder /app/build/libs/mvc-0.0.1.jar app.jar

EXPOSE 8080

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]

# Debug Mode
FROM eclipse-temurin:21-alpine AS dev

WORKDIR /app

COPY --from=builder /app/build/libs/mvc-0.0.1.jar app.jar

EXPOSE 8080
EXPOSE 5005

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "app.jar"]