FROM node:22-alpine AS builder

RUN npm install -g pnpm

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./
COPY astro.config.mjs ./
COPY .npmrc ./

RUN pnpm install

COPY . .

RUN pnpm run build

FROM node:22-alpine AS runner

RUN npm install -g pnpm

WORKDIR /app

COPY  --from=builder /app .

RUN chmod -R 755 /app/dist

EXPOSE 8080

USER node

CMD ["pnpm", "run", "preview","--host" ,"0.0.0.0"]